### ISSUE TITLE
Sanitize login and forms

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#10]
Use sanitizer

**Comment by meetinghouse** [comment]
Al,

Not sure what this means or if there is anything actionable here for me.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Viewed
