### ISSUE TITLE
ADMIN: Unable to save older project

### ISSUE THREAD

**Issue by meetinghouse** [alnutile/cms#16]
Having trouble saving projects that we have edited for user "Cassella Construction" - http://restorationtradesdirectory.com/user/cassella_construction

You'll see at this link that "no projects are available" if you are not logged in. If you are logged in as admin, however, you will see that Cassella Construction has several projects. That is issue number 1.

This user is a client who has changed their company name and construction emphasis, so we are trying to edit the projects to reflect that change.

However, even though you can see images when viewing the project while you're logged in, if you go to the edit view for the project, there are no images showing up in "Project Images" box at bottom - so when we try to edit anything and then save the changes, we get an error message: "project images field is required." 

This happens whether we are attempting to change the long description, delete the whole project, or just remove some of the images (of course we can make no headway in removing images, since none show up in the edit view).

It appears that these projects were imported from an older system in the past, so they may be different from other projects because of that.

For instance:

For The Willows project (http://restorationtradesdirectory.com/content/willows-brandows-point) we need to edit the long description

**Comment by alnutile** [comment]
@meetinghouse oops john this should go under the RTD project

**Comment by meetinghouse** [comment]
Sorry to have entered this in the wrong project. I am a bit lost in GitHub,
and thought I could send this to Andrew. Possible to do that?

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades
Directoryhttp://www.restorationtradesdirectory.com/
http://www.restorationtradesdirectory.com
(413) 773-8800

Published by:
Corbett Research Group https://mail.google.com/
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by alnutile** [comment]
Best to move the ticket. 
Just delete and make a new one for him under RTD GitHub area. 

If you look in the URL and see cms you are in the cms issue queue. 

Alfred Nutile
