### ISSUE TITLE
Banners Poll [Feature 5]

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#17]
https://docs.google.com/forms/d/1ndQs7tPJLiIFJi38a0SWY1Xd7yu6xe__-DBX3fSfbzQ/edit
This is the poll to verify if banners are working as expected

**Comment by alnutile** [comment]
From John

Per my recent, this is to confirm that we have redone your #5 poll, and failed to clear it, per my previous. Here are our notes:

## If there is one banner it will have the slider buttons and will be a static banner - No. I get one static banner when I have only one banner set as active, but it is not the active one.

## User can upload a banner - No. I can upload an image, but when I click Create, I get an error. Let me know where I can send a screenshot of this error if you need it.

Also, anytime I click Home Page from anywhere in the Admin Banners section, I get an error. Let me know where I can send a screenshot of this error also if you need it.

Let me know if you did NOT get our poll #5 results. I look forward to talk, tomorrow.

**Comment by alnutile** [comment]
item:
If there is one banner it will have the slider buttons and will be a static banner - No. I get one static banner when I have only one banner set as active, but it is not the active one.

Al 
This should be set now

item:
User can upload a banner - No. I can upload an image, but when I click Create, I get an error. Let me know where I can send a screenshot of this error if you need it

Al
Server had a permission issue should be set now

item:
Also, anytime I click Home Page from anywhere in the Admin Banners section, I get an error. Let me know where I can send a screenshot of this error also if you need it.

Al
This is now fixed it had to do with 1 banner which for some reason I did not catch in my tests

**Comment by meetinghouse** [comment]
Hello, Al, Katherine here. I am trying to verify your fixes for Poll 5, but
for whatever reason today I am unable to even hit the staging site. I just
get a blank white screen with "Redirecting" in the title tag. ???

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades
Directoryhttp://www.restorationtradesdirectory.com/
http://www.restorationtradesdirectory.com
(413) 773-8800

Published by:
Corbett Research Group https://mail.google.com/
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by meetinghouse** [comment]
Al,

Running test at http://cms.stagingarea.us/login, produces blank page w
"Redirect" at Title Tag. Can't clear your #5 (or 6) poll without access.
Please let me know what we are doing wrong.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
Sorry John there is a bug in my deployment script
let me look now

Al Nutile
http://alfrednutile.info/about
413.345.5103

**Comment by alnutile** [comment]
should be set now.
I will keep a better eye on that

Al Nutile
http://alfrednutile.info/about
413.345.5103

**Comment by alnutile** [comment]
Can we check in at 2 today instead of 2:30?

Al Nutile
http://alfrednutile.info/about
413.345.5103
