### ISSUE TITLE
Settings Poll [Feature 6]

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#18]
After banner poll is done and PASSES
https://docs.google.com/forms/d/1m5R3LVzEkUCt4gp1sazb6W9EkhMSrifr7NoXsyHrgak/viewform

**Comment by meetinghouse** [comment]
This is the error I get when I click the update button while doing this
poll.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades
Directoryhttp://www.restorationtradesdirectory.com/
http://www.restorationtradesdirectory.com
(413) 773-8800

Published by:
Corbett Research Group https://mail.google.com/
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by alnutile** [comment]
you will see a warning when in maintenance mode
https://www.dropbox.com/s/q23g8jhwi7z5amr/Screenshot%202014-05-15%2008.06.50.png

**Comment by alnutile** [comment]
@meetinghouse 
This is ready for review again
Going to assign it to you
Here are the items I fixed based on our meeting

FIXED settings name did not save e.g. company name

FIXED logged as test user should NOT see these links
user name is test3@gmail.com password = password

DONE Maintenance mode checkbox
  DONE this now swaps out blocked robots.txt for not blocked 
  DONE You will see a warning when in that mode
  DONE Only authenticated user can see the site anonymous use sees "Will be right back" sign

DONE social icons on the sidebar including google plus

DONE error when uploading a Logo

**Comment by alnutile** [comment]
Reply to some questions
Maintenance mode, will there be a way for the User to access the website, in Maintenance mode, when the DNS is NOT pointing at the server? Usually, the DNS will be pointing at the pre-existing website.

This is not about DNS. We can talk about that in another thread at a later time.
1. Robots.txt = disallow
2. The site is offline so that no content if facing the anonymous public user

Lets review on the phone today

**Comment by alnutile** [comment]
1. Re #18 (Poll 6), In general, we want to control all Title Tags separate from any other field. By Title Tag, we mean the "browser" field, the field that Google uses and links, in blue, in the Search Results page.

Al - Okay do you mean on all Pages and Portfolios? We can cover this in the meeting as well

**Comment by alnutile** [comment]
1. Re #18, (poll 6), are we limited to only the colors that can be displayed through colorfrog or can we edit stylesheets (css)?

This will come up later on in the theme thread. You can see that milestone here https://github.com/alnutile/cms/issues?milestone=7&state=open for later reference when we get to that part of the project and in the one an only google doc that contains all the scope

**Comment by alnutile** [comment]
1. Re #18 (poll 6), Repeating myself, but social icons still display when value removed from field. This is in the poll, and noted.

Bug noted and fixed in next deploy we can review in the meeting

**Comment by meetinghouse** [comment]
Al,

My question was not about DNS per se. I want to know can the User access
the website on the "staging server" or "in Maintenance mode" (however you
define it) before launch.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Al,

Title Tag is a critical element of SEO since Google gives it a great deal
of weight. Google can't rank websites with "fixed" Title Tags very well.

It is important that you and I understand what exactly I mean by the Title
Tag. It does NOT appear ON the web page itself, but rather in the BROWSER
and on the Google RESULTS PAGE.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Al,

This is a critical item as the stylesheet allows us to customize the
appearance of the website. Am I correct that you are saying that this item
will be addressed later? When will that be?

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Al,

Duly noted...

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748
