### ISSUE TITLE
Poll Portfolio and Projects [Feature 7]

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#22]
https://docs.google.com/forms/d/1J0_eVaNxXCAveLm1ZlF25E0ysyF7w3WyMdj1FEqbbnU/viewform

**Comment by meetinghouse** [comment]
Al,

I have received poll #7 and will complete...

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
Here is the feedback from the meeting

Some points here

This issue https://github.com/alnutile/cms/issues/18

## Follow up

Verify this is the first payment

Make a second field on all content types SEO Title
This will drive the SEO Title of the page

Remove Portfolio Link 

Upload 
/var/www/cms/site/2014-05-14_17-58-36/public/img/projects

http://cms.stagingarea.us/portfolios/1
Broken Page
Edit button on Pages/Projects/Portfolio
The image was in http://cms.stagingarea.us/portfolios/1/edit

Feedback on Portfolio page
http://cms.stagingarea.us/portfolios
no Portfolio Index just stick to the left nav
remove from seed data

Portfolio URL and Project URLS should 
make sure the URLs work with the slug
check / slash

Projects does to have a URL

Follow up Poll on URL settings

Set active portfolio you are on

Portfolio 1 seed

All projects have pages

So remove the Portfolio All Page

Site Map can be made from the All Projects Page
—title and link like a site map

Projects is driven by the url projects which comes from the Page Projects
This will show all projects
and the nav on the left side will show this on the bottom
So the final https://www.dropbox.com/s/yvxg1qldwg00rgz/Screenshot%202014-05-16%2011.22.59.png

Final output will be
https://www.dropbox.com/s/y9ls5p8mcni5v4s/Screenshot%202014-05-16%2011.23.15.png

Fix top nav so Portfolio is not there
Fix left so Projects go to Projects index based on the Pages slug

One banner = still same width

**Comment by alnutile** [comment]
@meetinghouse 
Back to you you have the next action.
Your actions include
1. make sure I got all items noted on the list above
2. make sure the URL works as expected eg if you edit a Project or Portfolio and set the URL to be /example_url then you visit http://cms.stagingarea.us/example_url it should show that page.

I will come back to any bugs you report here after the next invoice can be paid. Thanks!

**Comment by meetinghouse** [comment]
Al,

I completed Poll #7, Portfolios and Projects. Here are my notes. Some notes
may not be beyond the scope of the Poll, but I post them just in case they
are relevant.

##IMAGE PROJECT UPLOAD, produced errors at Create, but did work upon
Edit>>Upload. Multiple tests.
##SET URL, Worked for Portfolio, no field displays for Project Edit.
##TITLE TAG (SEO Title), not in Poll, but failed to display in all cases
except Portfolio One and was uneditable on that page.
##EDITING, all pages permit editing, except where noted above.
##ALL PROJECTS page, no data displays.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
More Feedback July 22 19:40
Redid Poll 7, failed to clear, posted a couple of notes re that failure.

Other issues that may be premature:
HTML import for wisiwig editor.
List All Projects at link.
SEO field display and edit.
URL edit for Projects.
We'll talk...

**Comment by acavanagh** [comment]
Issue 1 - CREATE PROJECT fails, produces "fatalerror"

This was recreated and should work now

**Comment by alnutile** [comment]
Issue 2 - The error should be gone while clicking on the link.

I think your other issues are done too. Can we do a check in on Thursday to see I got them all?
