### ISSUE TITLE
Add html insert button for Wysiwg

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#28]
so user can copy paste info from Paypal etc

**Comment by acavanagh** [comment]
there's a commercially available plugin for ckeditor that does exactly that -http://doksoft.com/soft/ckeditor-html-insert/demo.html.  Can we use that, or do you want me to roll something from scratch?

**Comment by acavanagh** [comment]
scratch the above, the mediaembed plugin will also accept javascript, should work fine for pasting in anything from youtube videos to paypal buttons.

**Comment by acavanagh** [comment]
finished, mediaembed plugin is enabled and works
