### ISSUE TITLE
If not logged in redirect back to login

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#3]
..

**Comment by alnutile** [comment]
this is now in place.
If you got to admin without being logged in it redirects you back to login to prevent this confusion

**Comment by meetinghouse** [comment]
I see that _If not logged in redirect back to login #3_ is resolved,
according to Github notes. No action.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748
