### ISSUE TITLE
Projects need a full page

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#30]
Like http://heatherandlittle.com/ the projects page needs to have the project and MANY images under the main info. With a link back to the Portfolio.
I will make a ticket for the multi image setup and will do that myself most likely.

Project Needs to have a SLUG and a Full Page
—links back to Portoflio
See http://heatherandlittle.com/ as an example
Images example on click use a jquery ui library for that
Example project page
https://www.dropbox.com/s/gvr98t1vnnps0dh/Screenshot%202014-07-24%2014.42.56.png

**Comment by acavanagh** [comment]
this is just waiting on the multiple images, which is assigned to Al

**Comment by alnutile** [comment]
Once I get the many images we need the text above the images
And then the many images under it liked the linked image above

**Comment by acavanagh** [comment]
many images are in.  What text above the image?  also not sure what you mean by 'And then the many images under it liked the linked image above'

**Comment by acavanagh** [comment]
I got it, talked to John today and cleared up my understanding of what he was looking for here.
