### ISSUE TITLE
Menus on left

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#33]
this is fine right now with portfolios
we want to hard code under these

Left menu notes
Home 
About us
Contact us
All projects on the bottom

Andy
use http://laravel.com/docs/responses View::share('name', 'Steve'); if possible to start passing this common theme variable

**Comment by acavanagh** [comment]
for all controller show methods add

```
public function show($portfolio = null)
  {
    parent::show();
```

and then in base controller show function,move in the logic from the shared sidebar menu view. pass static items, projects, and portfolios - even if it's an empty array
