### ISSUE TITLE
 Please add Delete Banner function 

### ISSUE THREAD

**Issue by acavanagh** [alnutile/cms#49]

**Comment by meetinghouse** [comment]
Andy,

Logged in, I don't see a Delete option for the Banners. Are we same version?

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
we might need to deploy the changes to the example site.  I'll check in 
with Al about that, I was under the impression that it was automated but 
that might not be fully implemented yet.  You can see the delete button 
here: http://cms.stagingarea.us/banners/1/edit; I'll talk to Al about 
deploying last nights code changes to the example site asap.

thanks,
Andy

**Comment by meetinghouse** [comment]
Andy,

I get it now! I'm not clear on the v deployment process...

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748
