### ISSUE TITLE
Authenticated user and change their email or password if needed

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#5]
https://docs.google.com/document/d/1LsuUYo1fNH7QgLhB6dmk0URYhr8_jsstUx0hfe4lD7I/edit#heading=h.bmwjcx44rqdq

**Comment by meetinghouse** [comment]
This links to doc\* [RTD] Outline of Goals and possible solutions (John
Corbett)*, not sure if anything is actionable for me at this link?

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
Sorry john just do the poll again to make sure I hit the goals. 

Alfred Nutile
