### ISSUE TITLE
Review User auth and user admin

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#6]
I have updated all the items per our notes from the last meeting you can take the poll here again. This is all about the goals listed in the first poll.

All links to the Poll and Docs are here
https://docs.google.com/forms/d/1213BULW9DInkWoBw6RgN46UpvPxx1ctaNWbzJMv4_T8/viewform
 logged in user can change their email or password without the help of admin.

**Comment by meetinghouse** [comment]
Al,

Thanks for the notes.

I understand that you are furnishing me with some actionable tasks, but I
am confused as to what they are. I have visited the links on your email and
I see documents there, but not sure what you would like me to do with those
documents. You seem to be relying upon a number of documents, but I don't
understand which ones are authoritative or require my attention

I understand that we are following up on your "poll", and that, perhaps
among other things, you would like me to test the user login UI. The links
at the original poll are all dead. Per your notes in Github, am I still to
test this doc? Does it live at a new URL?

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
John I fixed the deployment issue so now the demo site works. Sorry about that I will make sure to run better tests next time before I have you review it.

https://docs.google.com/forms/d/1213BULW9DInkWoBw6RgN46UpvPxx1ctaNWbzJMv4_T8/viewform

This is the poll then when done just come back here and reply done with poll/review

thanks

**Comment by meetinghouse** [comment]
Al,

Done, closed. On to #2? Let me know.

Thanks!

John C.
