### ISSUE TITLE
John to review Pages QA Poll

### ISSUE THREAD

**Issue by alnutile** [alnutile/cms#9]
## These "Static" pages come with all sites.

Home, About, Contact
## See the google doc for more info

https://docs.google.com/document/d/1LsuUYo1fNH7QgLhB6dmk0URYhr8_jsstUx0hfe4lD7I/edit#heading=h.98qt5w5r7fvo For items in _Phase 1 marked [Feature 2]_
## Lastly here is the related Poll

https://docs.google.com/forms/d/1duzdtJXbrvt-M1oR_AGEr8tQsv6RA3sP4F33bYCqw7o/viewform

**Comment by meetinghouse** [comment]
Al,

Will review your links and let you know any issues.

Will also review the "RTD Outline..." doc to see if your responded to any
of my comments.

ACTIONABLE: Please respond to my requests for guidance on yr requested pmt
- \- funds are immediately available.

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
@meetinghouse you get a chance to do the poll? Thought you did but I do not see it. I will be ready to Poll the WYSIWYG right after we are done with this.

**Comment by meetinghouse** [comment]
Al,

Perhaps this has to do with what docs are authoritative. I did "a" poll
over the weekend, can't say for sure that it was "the" poll.

[?]

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
Seems like I pasted the wrong url, sorry about that. The new poll is here
https://docs.google.com/forms/d/1duzdtJXbrvt-M1oR_AGEr8tQsv6RA3sP4F33bYCqw7o/viewform
I updated the github issue to reference this as well.

Al Nutile
http://alfrednutile.info/about
413.345.5103

**Comment by meetinghouse** [comment]
Al,

Got it! Will turn around...

[?]

Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  mailto:John@RestorationTrades.comJohn@RestorationTrades.com
Phone: 413-586-4748

**Comment by alnutile** [comment]
Cool, let me know if you want to do a screen share.
After that the WYSIWYG is ready to review.
https://github.com/alnutile/cms/issues/11

Thanks

Al Nutile
http://alfrednutile.info/about
413.345.5103
